### ISSUE TITLE
the spell Taste for Blood is bugged  

### ISSUE THREAD

**Issue by cnmir2** [TrinityCoreLegacy/TrinityCore#12]
**Description**:
 the spell Taste for Blood is bugged   56636 56637 56637  
**Current behaviour**: Tell us what happens
rend could not chance  allow the overpower 
**Expected behaviour**: Tell us what should happen instead
http://www.wowhead.com/spell=124326
**Steps to reproduce the problem**:

1. 
2. 
3. 

**TC hash/commit**:  

**TDB version**:  

**Operating system**:  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
the bug tracker for 4.3.4 is https://gitlab.com/trinitycore/TrinityCore_434/issues
