### ISSUE TITLE
A question 

### ISSUE THREAD

**Issue by MehdiAria** [TrinityCoreLegacy/TrinityCore#18]
**Description**: It's not an issue or a problem. All I want to know is which version on TC 4.3.4 is compile-able with visual studio 2013?

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**TC hash/commit**:  

**TDB version**:  

**Operating system**:  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
No, you need 2015.
