### ISSUE TITLE
Complile errors VS2013

### ISSUE THREAD

**Issue by killradio** [TrinityCoreLegacy/TrinityCore#5]
**Description**: Same errors from this issue: https://github.com/TrinityCore/TrinityCore/issues/17260

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**: Compile errors

**TC hash/commit**:  https://github.com/TrinityCoreLegacy/TrinityCore/commit/f8862f19f5523e0e8b851fdca96b65f6018087a5

**Operating system**:  win x32

**Comment by Aokromes** [comment]
This tracker is open for telenpc3, for trinitycore 4.3.4 you must use gitlab, anyway support for 2013 will be dropped on TC on few weeks, so i decided not to port that hackfix for 2013.

**Comment by Bodeguero** [comment]
@Aokromes fixed in VS 2015?

**Comment by Aokromes** [comment]
Unless i broke something lately, it must work on 2015.

**Comment by Bodeguero** [comment]
@Aokromes  thx
