### ISSUE TITLE
Work until 606c64bae5a6. Any update make client crash

### ISSUE THREAD

**Issue by ConradBunton** [TrinityCoreLegacy/TrinityCore#7]
606c64bae5a6 (2016-09-21 7h40) is the last for me. It's works but all update makes client crash. Tried to delete all and download to make a clean recompil... Always that client crash.

Win 64
Boost 1.61.0
OpenSSL 1.0.2f
MSVC 14

When I launch the 606c64bae5a6 and keep DB, Config... Everything is ok, it's work.

Client error message :
This application has encountered a critical error:
ERROR #132 (0x851000084) Fatal exeption!

**Comment by Aokromes** [comment]
There is no such rev on TrinityCore 4.3.4

**Comment by Aokromes** [comment]
Also, works for me on 4.3.4:

http://i.imgur.com/GSW1zUm.jpg

And this is not tc 4.3.4 bug report.

**Comment by ConradBunton** [comment]
I found the problem. Warden option active...
